name: todo_app
services:
  todo_service:
    build: .
    volumes:
      - .:/home/todo-project
    ports:
      - 8001:8000
    image: elmoghany/todo_app:v1.6-django-docker-compose
    container_name: todo_django
    command: ["python", "todo_project/manage.py", "runserver", "0.0.0.0:8000"]
